enable_cache: False

settings:
  docker:
    required_integrations:
      - mlflow

# Configuration of the Model Control Plane
model:
  name: anomaly_detector
  license: Apache 2.0
  description: Network anomaly detection using GPU-accelerated XGBoost
  tags: ["classification", "anomaly_detection", "network_security", "xgboost"]

# Data configuration
data:
  file_path: "data/kddcup.data.corrected"
  test_size: 0.25
  random_state: 42
  reduce_anomalies: False
  anomaly_percentage: 0.01

# Feature configuration
features:
  categorical_vars:
    - protocol_type
    - service
    - flag
    - land
    - logged_in
    - is_host_login
    - is_guest_login
  column_names:
    - duration
    - protocol_type
    - service
    - flag
    - src_bytes
    - dst_bytes
    - land
    - wrong_fragment
    - urgent
    - hot
    - num_failed_logins
    - logged_in
    - num_compromised
    - root_shell
    - su_attempted
    - num_root
    - num_file_creations
    - num_shells
    - num_access_files
    - num_outbound_cmds
    - is_host_login
    - is_guest_login
    - count
    - srv_count
    - serror_rate
    - srv_serror_rate
    - rerror_rate
    - srv_rerror_rate
    - same_srv_rate
    - diff_srv_rate
    - srv_diff_host_rate
    - dst_host_count
    - dst_host_srv_count
    - dst_host_same_srv_rate
    - dst_host_diff_srv_rate
    - dst_host_same_src_port_rate
    - dst_host_srv_diff_host_rate
    - dst_host_serror_rate
    - dst_host_srv_serror_rate
    - dst_host_rerror_rate
    - dst_host_srv_rerror_rate
    - label

# Model configuration
xgboost:
  binary_classification:
    num_rounds: 10
    max_depth: 8
    max_leaves: 256
    alpha: 0.9
    eta: 0.1
    gamma: 0.1
    learning_rate: 0.1
    subsample: 1
    reg_lambda: 1
    scale_pos_weight: 2
    tree_method: "gpu_hist"
    n_gpus: 1
    objective: "binary:logistic"
    verbose: True
  
  multiclass_classification:
    num_rounds: 10
    max_depth: 8
    max_leaves: 256
    alpha: 0.9
    eta: 0.1
    gamma: 0.1
    learning_rate: 0.1
    subsample: 1
    reg_lambda: 1
    tree_method: "gpu_hist"
    n_gpus: 1
    objective: "multi:softprob"
    verbose: True

# Evaluation configuration
evaluation:
  binary_threshold: 0.5
  metrics:
    - accuracy
    - auc
    - confusion_matrix
    - classification_report
    - feature_importance

# Deployment configuration
deployment:
  model_name: "anomaly_detector"
  service_workers: 3
  prediction_threshold: 0.5